apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ovirtimageiopopulators.forklift.konveyor.io
spec:
  group: forklift.konveyor.io
  names:
    kind: OvirtImageIOPopulator
    listKind: OvirtImageIOPopulatorList
    plural: ovirtimageiopopulators
    singular: ovirtimageiopopulator
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: OvirtImageIOPopulator is a specification for a OvirtImageIOPopulator resource
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          spec:
            description: OvirtImageIOPopulatorSpec is the spec for a OvirtImageIOPopulator resource
            properties:
              engineUrl:
                type: string
              engineSecretName:
                type: string
              diskId:
                type: string
            required:
            - engineUrl
            - engineSecretName
            - diskId
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

