apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-pop-pvc1
  namespace: default
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  dataSourceRef:
    apiGroup: forklift.konveyor.io
    kind: OvirtImageIOPopulator
    name: ovirt-imageio1
