apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-ceph-pvc2
  namespace: default
spec:
  storageClassName: csi-rbd-sc
  volumeMode: Block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  dataSourceRef:
    apiGroup: forklift.konveyor.io
    kind: OvirtImageIOPopulator
    name: vol-ceph-cr2
